// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNzE2tBZOJMnBV_4OuvwPSFzvmmSRtBKw',
    appId: '1:1056261364081:web:84fefc53e17e6939d87ed0',
    messagingSenderId: '1056261364081',
    projectId: 'safeher-75486',
    authDomain: 'safeher-75486.firebaseapp.com',
    storageBucket: 'safeher-75486.firebasestorage.app',
    measurementId: 'G-3P01T5N87R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr-Z6NwA9wZ7j470F4nihnUuLruxqgBNA',
    appId: '1:1056261364081:android:7aa5b3bfe3e14031d87ed0',
    messagingSenderId: '1056261364081',
    projectId: 'safeher-75486',
    storageBucket: 'safeher-75486.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-LLq4LQkgdKkWeEi3LxP699qsHGKvEM',
    appId: '1:728346056859:ios:51dbe4f2c7fcb712f54e3e',
    messagingSenderId: '728346056859',
    projectId: 'safeher-51996',
    storageBucket: 'safeher-51996.firebasestorage.app',
    iosBundleId: 'com.example.safeherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq-LLq4LQkgdKkWeEi3LxP699qsHGKvEM',
    appId: '1:728346056859:ios:51dbe4f2c7fcb712f54e3e',
    messagingSenderId: '728346056859',
    projectId: 'safeher-51996',
    storageBucket: 'safeher-51996.firebasestorage.app',
    iosBundleId: 'com.example.safeherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-1M3uPG72FvmLJSDtzYS3-9nMAtK4KRg',
    appId: '1:728346056859:web:c4df7fd9a92cd187f54e3e',
    messagingSenderId: '728346056859',
    projectId: 'safeher-51996',
    authDomain: 'safeher-51996.firebaseapp.com',
    storageBucket: 'safeher-51996.firebasestorage.app',
    measurementId: 'G-GFYBTSLLVN',
  );
}
